name: 'Setup JMeter'
description: 'Setup selected version of Jmeter'
inputs:
  jmeter_version:
    description: 'Jmeter version to install'
    required: true
    default: '5.6.2'
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Select the Jmeter version
      id: jmeter
      shell: bash
      run: |
        cd /home/ubuntu/
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.zip
        unzip apache-jmeter-5.6.2.zip
        cd apache-jmeter-5.6.2
        bin/jmeter -v

