name: 'Setup JMeter'
description: 'Setup selected version of Jmeter'
inputs:
  jmeter_version:
    description: 'Jmeter version to install'
    required: true
    default: '5.6.2'
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Select the Jmeter version
      shell: bash
      run: |
        echo "final_version=${{inputs.jmeter}}" >> $GITHUB_ENV
        echo $GITHUB_ENV
        echo $final_version